issuer: https://token.actions.githubusercontent.com
subject_pattern: "repo:Pinguteca/sdk-core-go:ref:refs/heads/main"
claim_pattern:
  workflow_ref: "Pinguteca/sdk-core-go/\\.github/workflows/build-(go|dotnet)\\.yml@refs/heads/main"
permissions:
  contents: read
