name: Lint GitHub Actions

on:
  push:
    branches: [main]
    paths:
      - ".github/zizmor.yml"
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
    paths:
      - ".github/zizmor.yml"
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: Analyze workflows
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      security-events: write # zizmor and actionlint upload SARIF to GitHub Code Scanning
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
          disable-telemetry: "true"
          disable-sudo: "true"
      - name: Obtain release token
        id: octo-sts
        uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        with:
          scope: Pinguteca/sdk-core-go
          identity: lint-gha
      - name: Optimize Git config for CI
        run: |
          git config --global core.compression 0
          git config --global core.fsync -all
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: |
            .github/workflows
            .github/zizmor.yml
          sparse-checkout-cone-mode: false
          filter: "blob:none"
          token: ${{ steps.octo-sts.outputs.token }}
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0
        with:
          config: .github/zizmor.yml
      - name: Run actionlint via reviewdog
        uses: reviewdog/action-actionlint@50842263c20a7c46bd0065b9e624d3c569db061e # v1.73.0
