name: Lint GitHub Actions

on:
  push:
    branches: [main]
    paths:
      - ".github/zizmor.yml"
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
    paths:
      - ".github/zizmor.yml"
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: Analyze workflows
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit
          disable-telemetry: "true"
          disable-sudo-and-containers: "true"
      - name: Optimize Git config for CI
        run: |
          git config --global core.compression 0
          git config --global core.fsync -all
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          sparse-checkout: |
            .github/workflows
            .github/zizmor.yml
          sparse-checkout-cone-mode: false
          filter: "blob:none"
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@b572f7b1a1c2d41efaab43d504f68d215c3cd727 # v0.5.4
        with:
          config: .github/zizmor.yml
      - name: Run actionlint via reviewdog
        uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72.0
